### ISSUE TITLE
关于RuntimeError: One or more background workers are no longer alive. 

### ISSUE THREAD

**Issue by koma1987** [ge-xing/SegMamba#51]
您好，我在运行 训练步骤时，出现了这一个错误
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message，请问一下该如何解决呢，谢谢

**Comment by ge-xing** [comment]
这个不是具体错误，你先看看有没有其他错误 往上翻一下日志。

**Comment by koma1987** [comment]
你好，感谢回复，整个错误信息是这样的：
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/root/miniconda3/envs/lab/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/lab/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/lab/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/root/miniconda3/envs/lab/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by ge-xing** [comment]
你是跑完了吧？如果没有其他报错信息，跑完了就会出现这个 没问题的。
