### ISSUE TITLE
您好 training问题

### ISSUE THREAD

**Issue by Heartnlh1** [ge-xing/SegMamba#58]
Epoch 0:   0%|                                          | 0/250 [00:00<?, ?it/s]Exception in background worker 5:
 expected np.ndarray (got numpy.ndarray)
Traceback (most recent call last):
  File "/home/miniconda3/envs/segmamba/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 55, in producer
    item = transform(**item)
  File "/home/miniconda3/envs/segmamba/lib/python3.10/site-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/home/miniconda3/envs/segmamba/lib/python3.10/site-packages/batchgenerators/transforms/utility_transforms.py", line 66, in __call__
    data_dict[key] = self.cast(torch.from_numpy(data_dict[key])).contiguous()
TypeError: expected np.ndarray (got numpy.ndarray)

在training的代码运行过程中遇到了numpy的报错，这是numpy版本的问题吗，但我试了很多版本都不行

**Comment by ge-xing** [comment]
更新下numpy
